### ISSUE TITLE
Running CNTools in offline mode

### ISSUE THREAD

**Issue by thejoshsmith** [ststolz/Cardano-Node-Docker#1]
Hey @ststolz, first of all thanks for putting together this awesome image!

I have everything working perfectly except running cntools.sh offline. When I run `docker run --rm -it -v ${PWD}/priv:/opt/cardano/cnode/priv -v ${PWD}/tmp:/tmp  ststolz/cardano-node bash -c 'echo 117 > "/opt/cardano/cnode/guild-db/shelley_trans_epoch" && cntools.sh -o'` it seems to run the usual relay node script and gets stuck on `Listening on http://127.0.0.1:12798`.

I'm running that particular command using Docker on OSX Big Sur if that's any help.

Let me know if I'm missing a step and/or you need any more information.

**Comment by ststolz** [comment]
Can you try to use `--entrypoint` for the command? Also keep care to use the latest version by using tag `ststolz/cardano-node:1.25.1`.

**Comment by ststolz** [comment]
And please also try only `--entrypoint bash`. Maybe `echo 117` is not needed anymore. Have at the moment no time to try.

**Comment by ststolz** [comment]
Tested. Try 

```bash
docker run --rm -it -v ${PWD}/priv:/opt/cardano/cnode/priv -v ${PWD}/tmp:/tmp ststolz/cardano-node --entrypoint /opt/cardano/cnode/scripts/cntools.sh ststolz/cardano-node:1.25.1 -o
```

This should do the job. Please give feedback, so that I can update README.md.

**Comment by thejoshsmith** [comment]
Thanks @ststolz, I had to tweak the command to:
`docker run --rm -it -v ${PWD}/priv:/opt/cardano/cnode/priv -v ${PWD}/tmp:/tmp --entrypoint /opt/cardano/cnode/scripts/cntools.sh ststolz/cardano-node:1.25.1 -o`

It works fine on my server but on my Mac I get:

`cardano-cli: Network.Socket.connect: <socket: 11>: does not exist (No such file or directory)Testing chattr access permission, enter user password if requested...
chattr: Function not implemented while reading flags on /tmp/cnode/cntools/test

WARN: Elevated privileges needed for chattr command used to write protect wallet and pool keys
Add required sudo permissions or run the following command to add passwordless sudo access to chattr command for 'root' user

echo "root ALL=NOPASSWD: /usr/bin/chattr" | sudo tee /etc/sudoers.d/cntools

CNTools terminated, cleaning up...`

Any idea what that might be?

**Comment by ststolz** [comment]
No idea, because I only use Linux. Do you execute docker as root on your Mac?

**Comment by ststolz** [comment]
What is the reason you use Mac? I would recommend installing Ubuntu Server encrypted on a SSD USB drive and boot this as your cold storage. The docker image you can transfer with USB to your cold storage.

**Comment by thejoshsmith** [comment]
Thanks @ststolz, I have indeed done just that! I was using my Mac with testnet to experiment with signing transactions "offline" but I've now gone down the Ubuntu Server route.

Thanks once again for the awesome Docker image.
